import { Transaction } from "@/types/type";

export const transactions: Transaction[] = [
    {
        id: "1",
        amount: -45.5,
        merchant: "Whole Foods",
        category: "Groceries",
        date: "2024-02-10",
        status: "completed",
    },
    {
        id: "2",
        amount: -120.0,
        merchant: "Shell Gas Station",
        category: "Transportation",
        date: "2024-02-09",
        status: "completed",
    },
    {
        id: "3",
        amount: +60.25,
        merchant: "Starbucks",
        category: "Dining",
        date: "2024-02-08",
        status: "pending",
    },
    {
        id: "4",
        amount: -15.0,
        merchant: "Netflix",
        category: "Entertainment",
        date: "2024-02-07",
        status: "completed",
    },
    {
        id: "5",
        amount: -250.0,
        merchant: "Hospital Pharmacy",
        category: "Healthcare",
        date: "2024-02-06",
        status: "to be paid",
    },
    {
        id: "6",
        amount: -75.5,
        merchant: "Zara",
        category: "Shopping",
        date: "2024-02-05",
        status: "failed",
    },
    {
        id: "7",
        amount: -90.0,
        merchant: "Uber",
        category: "Transportation",
        date: "2024-02-04",
        status: "completed",
    },
    {
        id: "8",
        amount: -35.0,
        merchant: "Trader Joe's",
        category: "Groceries",
        date: "2024-02-03",
        status: "completed",
    },
    {
        id: "9",
        amount: +120.0,
        merchant: "AMC Theaters",
        category: "Entertainment",
        date: "2024-02-02",
        status: "pending",
    },
    {
        id: "10",
        amount: -50.0,
        merchant: "CVS",
        category: "Healthcare",
        date: "2024-02-01",
        status: "reversed",
    },
    {
        id: "11",
        amount: -20.0,
        merchant: "McDonald's",
        category: "Dining",
        date: "2024-01-31",
        status: "completed",
    },
    {
        id: "12",
        amount: -300.0,
        merchant: "IKEA",
        category: "Shopping",
        date: "2024-01-30",
        status: "to be paid",
    },
    {
        id: "13",
        amount: -80.0,
        merchant: "Exxon",
        category: "Transportation",
        date: "2024-01-29",
        status: "failed",
    },
    {
        id: "14",
        amount: +55.0,
        merchant: "Whole Foods",
        category: "Groceries",
        date: "2025-01-28",
        status: "completed",
    },
    {
        id: "15",
        amount: -40.0,
        merchant: "Pizza Hut",
        category: "Dining",
        date: "2024-01-27",
        status: "completed",
    },
    {
        id: "16",
        amount: -60.0,
        merchant: "Spotify",
        category: "Entertainment",
        date: "2024-01-26",
        status: "pending",
    },
    {
        id: "17",
        amount: -180.0,
        merchant: "CVS",
        category: "Healthcare",
        date: "2024-06-25",
        status: "completed",
    },
    {
        id: "18",
        amount: -200.0,
        merchant: "Amazon",
        category: "Shopping",
        date: "2024-09-24",
        status: "to be paid",
    },
    {
        id: "19",
        amount: +100.0,
        merchant: "Shell Gas Station",
        category: "Transportation",
        date: "2025-09-23",
        status: "completed",
    },
    {
        id: "20",
        amount: -30.0,
        merchant: "Trader Joe's",
        category: "Groceries",
        date: "2025-04-22",
        status: "reversed",
    },
    {
        id: "21",
        amount: -25.0,
        merchant: "Burger King",
        category: "Dining",
        date: "2025-08-21",
        status: "completed",
    },
    {
        id: "22",
        amount: -70.0,
        merchant: "H&M",
        category: "Shopping",
        date: "2024-01-20",
        status: "failed",
    },
    {
        id: "23",
        amount: -15.0,
        merchant: "Starbucks",
        category: "Dining",
        date: "2024-01-19",
        status: "completed",
    },
    {
        id: "24",
        amount: -50.0,
        merchant: "Netflix",
        category: "Entertainment",
        date: "2024-01-18",
        status: "completed",
    },
    {
        id: "25",
        amount: -90.0,
        merchant: "CVS",
        category: "Healthcare",
        date: "2024-01-17",
        status: "pending",
    },
    {
        id: "26",
        amount: +120.0,
        merchant: "Con Edison",
        category: "Utilities",
        date: "2025-05-16",
        status: "completed",
    },
    {
        id: "27",
        amount: -65.0,
        merchant: "Domino's Pizza",
        category: "Dining",
        date: "2025-11-15",
        status: "pending",
    },
    {
        id: "28",
        amount: -220.0,
        merchant: "Best Buy",
        category: "Shopping",
        date: "2024-01-14",
        status: "to be paid",
    },
    {
        id: "29",
        amount: -80.0,
        merchant: "PG&E",
        category: "Utilities",
        date: "2025-08-13",
        status: "failed",
    },
    {
        id: "30",
        amount: +45.0,
        merchant: "Whole Foods",
        category: "Groceries",
        date: "2024-01-12",
        status: "reversed",
    },

];